spring:
  application:
    name: dgs-example

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics

logging:
  level:
    com.netflix.graphql.dgs.example: DEBUG

dgs:
  graphql:
    disallow-mutation-over-get:
      enabled: false