name: Qodana
on:
  workflow_dispatch:
  pull_request:
jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - id: get-java-home-17
        run: echo "JAVA_HOME_17_X64=$JAVA_HOME_17_X64" >> $GITHUB_OUTPUT
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.2
        with:
          args: -v,${{ steps.get-java-home-17.outputs.JAVA_HOME_17_X64 }}:/root/.jdks/jdk17, --script, "/opt/idea/bin/idea.sh installPlugins com.netflix.spring.intellij.spring-boot-netflix-intellij-plugin https://artifacts.netflix.net/devtools/sbn-intellij/updatePlugins.xml"
          push-fixes: pull-request
          upload-result: true
        env:
          QODANA_LICENSE: ${{ secrets.QODANA_LICENSE }} # read the steps about it below