name: Qodana
on:
  workflow_dispatch:
  pull_request:
jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.2
        with:
          args: --apply-fixes
          push-fixes: pull-request
        env:
          QODANA_LICENSE: ${{ secrets.QODANA_LICENSE }} # read the steps about it below
